# Generated by Django 3.2.4 on 2021-11-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211116_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('15', 'QuanAo'), ('17', 'TuiVi'), ('2', 'Camera'), ('10', 'MayGiat'), ('21', 'XeTai'), ('19', 'XeDapDien'), ('16', 'TuLanh'), ('0', 'Amply'), ('4', 'DienThoai'), ('13', 'NuocHoa'), ('6', 'GiayDep'), ('11', 'MayLanh'), ('12', 'MayTinhBang'), ('18', 'XeDap'), ('7', 'GiuongNem'), ('14', 'Oto'), ('20', 'XeMay'), ('5', 'DongHo'), ('9', 'Laptop'), ('3', 'CayCanh'), ('1', 'BanGhe'), ('8', 'KeTu')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
